### ISSUE TITLE
Few issues with .prompt div on mobile

### ISSUE THREAD

**Issue by mr-null-byter** [aaaaalexis/obsidian-cupertino#243]
The following issues are related to Omnisearch, but I think the original issue is with `.prompt`. The bugs with Omnisearch are
1. Can't close it, similar to #205. I know it was mentioned that Omnisearch should implement a close button, but this is not an issue with other themes, so it's certainly a theme issue.
2. Contents of Omnisearch overflow the horizontal bounds, leading to horizontal scrolling in addition to vertical scrolling.
3. Content box of Omnisearch runs through the search bar, which is aesthetically confusing as search content and query text overlap.

Below is my hot-fix attempt, which fixes all the above issues on _my_ iPhone. It's hyper-specific to my phone with all the random numerical values I've set. I'm sure a more robust, generalizable solution exists! This just proves the issue should be fixed by Cupertino!

```css
@media only screen and (max-width: 600px) {
  .prompt {
    width: fit-content;
    max-width: 95vw !important;
    max-height: 40vh !important;
    margin: -100px 10px 10px 10px !important;
    position: relative;
    overflow-wrap: break-word !important;
    word-break: break-all !important;
  }
}
```

<div align="center">
<img src="https://github.com/user-attachments/assets/83a2cf29-b2b4-4cb5-928e-d7ec3b2e7a31" width=300px>
</div>

**Comment by svnaxis** [comment]
Beautiful solution, I've implemented this, thanks for the suggestion!

**Comment by mr-null-byter** [comment]
@aaaaalexis Nice 👍🏼! Though maybe test it for robustness? I was quite hacky with my `max-height`, `max-width`, and `margin` values. While the first two should scale with phone display size, the margin might not! Will it work for smaller and bigger phones?! Idk! 🤷🏻

**Comment by mr-null-byter** [comment]
@aaaaalexis Perhaps we should open this issue again as it’s not fixed on v2.5.3. Looking at the css, I see specific numerical values for positioning, which makes sense why it doesn’t generalize to all screens.

This is how Omnisearch looks on iPhone 13 on v2.5.3 (no other snippets enabled). 

<img width="300" height="600" src="https://github.com/user-attachments/assets/e56a29ec-b8b7-4c5f-a29a-4abdb0aea42b" />

**Comment by svnaxis** [comment]
… doesn’t work on my iPhone 17 either. Seems like the desktop emulation is entirely different from the actually mobile app

**Comment by svnaxis** [comment]
Should be fixed this time, can comfirm it works on my phone. You need to reinstall the theme though as the version number is still 2.5.3 (not yet pushed now)
