### ISSUE TITLE
Canvas notes texts overlaps line numbers

### ISSUE THREAD

**Issue by lhnrd** [aaaaalexis/obsidian-cupertino#253]
Hey 👋 

Appreciate very much the quick response about the line number on another issue. It looks great now. Ty!
As I was using Canvas in Obsidian I've noticed now that the text overlaps the line numbers.

I've tried to find the setting to change without luck, decided to open this issue. 

## Minimal

![Image](https://github.com/user-attachments/assets/859909e0-709c-4ef1-bc2a-a66dfd93943d)

## Cupertino

![Image](https://github.com/user-attachments/assets/f013cfa2-f26d-4dc9-92b1-112d567e5963)

**Comment by svnaxis** [comment]
Fixed. I didn't know Canvas supports line number as well

**Comment by lhrnd0** [comment]
@aaaaalexis I've updated but still appears to overlap on two digit numbers

<img width="228" height="676" alt="Image" src="https://github.com/user-attachments/assets/5c6aab90-a673-487d-bd8c-41b102b6140a" />

**Comment by svnaxis** [comment]
I can't reproduce it 

<img width="574" height="922" alt="Image" src="https://github.com/user-attachments/assets/aa404291-61f0-451d-b7b4-a788f3cacfa4" />

**Comment by lhrnd0** [comment]
@aaaaalexis Hmm, interesting. Had to use this snippet of code to solve

```css
body:not(.is-mobile) .cm-gutters {
  position: static !important;
}
```

But then it breaks the line numbers on the left in normal notes

**Comment by svnaxis** [comment]
Try update again, which version are you on?

**Comment by lhrnd0** [comment]
@aaaaalexis updated and it works great now, appreciate the fix. Ty!
