### ISSUE TITLE
Can callouts with headings be formatted better?

### ISSUE THREAD

**Issue by Buddinski88** [aaaaalexis/obsidian-cupertino#34]
During my research I came across the Ideaverse Vault by Nick Milo and he also uses headings in callouts. Example:

![image](https://github.com/user-attachments/assets/b379af96-f404-43e5-8e58-d5bb3e4e2e22)

```mardown
> [!Map]- # Atlas
> > *Where would you like to go?*
> 
> - To do inspired work, go to [[Add]], [[Relate]], and [[Communicate]].
>   
> ![[mckie-ship-and-sea-mid-narrow-.jpg|400]]
> - To launch into your knowledge, try out: [[Library]] | [[People Map]] | [[Sources Map]].
> - To catalyze your mind, go to your [[Thinking Map]] and [[Concepts Map]]. 
> - For grounding, [[Life Map]]. For training, [[Ideaverse Map]]. For rules, [[Meta PKM]].
```
If you take over the callout, the Cupertino theme looks less than appealing.

![image](https://github.com/user-attachments/assets/44b13f3a-09b6-4c75-88dd-d64a11c83934)

**Comment by aaaaalexis** [comment]
Title spacing is fixed https://github.com/aaaaalexis/obsidian-cupertino/commit/ba9e0092f2b2c08273c5388542f7a983a0b62bef, I'll adjust background color next update, but no plans to style callouts further for now.

**Comment by iwa** [comment]
still not fixed tho?
tried the example used by OP, and i'm having the same issue even though i'm on 1.3.2

![image](https://github.com/user-attachments/assets/749b2cb8-197d-4ca4-b01a-d7635c3f604a)

**Comment by aaaaalexis** [comment]
1.3.3 pushed, please check if it's fixed. This is how it looks like on my end:
![image](https://github.com/user-attachments/assets/d6cf9a8b-1094-4a4c-9c6e-760493bd115e)

If the issue persists I would say it's plugins.

**Comment by Buddinski88** [comment]
> pushed, please check if it's fixed. This is how it looks like on my end:

Thank you very much! With the new version (without further changes) it is also displayed correctly for me. From my point of view the issue should be closed 👍

**Comment by aaaaalexis** [comment]
Great. @iwa can you confirm?

**Comment by iwa** [comment]
yup i can confirm it's good now! thanks

**Comment by aaaaalexis** [comment]
Thank all for reporting!
