### ISSUE TITLE
Status bar and close button missing on 1.4.3

### ISSUE THREAD

**Issue by milosm** [aaaaalexis/obsidian-cupertino#66]
Hi,

First of all, great theme! Thank you for making and supporting it!

I just updated to version 1.4.3 and noticed two things after the update was applied:
- The close button (x in the top right corner) of the settings window is missing.
- The status bar isn't shown at all (I toggled the 'Always show status bar' setting just to make sure).

I thought it would be good to report what I noticed.

Thanks!

**Comment by milosm** [comment]
More info:
- Described above is for a Mac.
- On Windows, the status bar is visible, but the close settings button isn't.
- On iOS, both appear ok.

**Comment by aaaaalexis** [comment]
Fixed in 1.4.4 https://github.com/aaaaalexis/obsidian-cupertino/commit/86192a9dd779e9a9a591c7f6a7d8bf870a96d779 https://github.com/aaaaalexis/obsidian-cupertino/commit/2c07f6daa0b350adc0efa87dff686ecad5393465

**Comment by tjstankus** [comment]
I've updated Cupertino and restarted Obsidian. The status bar still isn't appearing. Am I missing something?

**Comment by aaaaalexis** [comment]
@tjstankus Can you share a screenshot?

**Comment by tjstankus** [comment]
@aaaaalexis Of course! And thank you for your work. I just started using this theme and it's really well done.

<img width="1504" alt="Image" src="https://github.com/user-attachments/assets/a808c0f1-a3ec-45bc-b4d0-15483982c757" />

**Comment by aaaaalexis** [comment]
@tjstankus The status bar is the dark bar on the bottom that you can hover on. If you want to show it at all times, you can enable "Always show in status bar" in Style Settings

**Comment by tjstankus** [comment]
@aaaaalexis Ugh, I didn't know about that style setting. Thank you and sorry to waste your time on this.

**Comment by aaaaalexis** [comment]
Figured it's a big unclear. Status bar will now flash on startup to indicate its location
